######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 18 14:20:02 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += config.h desktopfile.h
SOURCES += desktopfile.cpp main.cpp
